// Code generated by "stringer -type=EpisodeType"; DO NOT EDIT.

package query

import "strconv"

const _EpisodeType_name = "EpUnknownEpRegularEpSpecialEpCreditEpTrailerEpParodyEpOther"

var _EpisodeType_index = [...]uint8{0, 9, 18, 27, 35, 44, 52, 59}

func (i EpisodeType) String() string {
	if i < 0 || i >= EpisodeType(len(_EpisodeType_index)-1) {
		return "EpisodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EpisodeType_name[_EpisodeType_index[i]:_EpisodeType_index[i+1]]
}
