// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Anime struct {
	Aid          int64
	Title        string
	Type         string
	Episodecount int64
	Startdate    sql.NullInt64
	Enddate      sql.NullInt64
}

type Episode struct {
	Eid         int64
	Aid         int64
	Type        int64
	Number      int64
	Title       string
	Length      int64
	UserWatched int64
}

type EpisodeFile struct {
	ID   int64
	Eid  int64
	Path string
}

type Filehash struct {
	Size     int64
	Hash     string
	Eid      sql.NullInt64
	Aid      sql.NullInt64
	Filename sql.NullString
}

type Watching struct {
	Aid    int64
	Regexp string
	Offset int64
}
