// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Anime struct {
	Aid          AID
	Title        string
	Type         string
	Episodecount int
	Startdate    sql.NullInt64
	Enddate      sql.NullInt64
}

type Episode struct {
	Eid         EID
	Aid         AID
	Type        EpisodeType
	Number      int
	Title       string
	Length      int
	UserWatched bool
}

type EpisodeFile struct {
	ID   int64
	Eid  EID
	Path string
}

type Filehash struct {
	Size     int64
	Hash     Hash
	Eid      EID
	Aid      AID
	Filename string
}

type Watching struct {
	Aid    AID
	Regexp string
	Offset int
}
